/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)
}

private data class Candidate(
    val credentialId: String,
    val claimName: String
)

fun planPresentation(
    wallet: Wallet,
    request: PresentationRequest,
    trustedIssuers: Set<String>,
    nowEpochSeconds: Long
): PresentationPlan {
    val missingClaims = mutableSetOf<String>()
    val untrustedCredentials = mutableSetOf<String>()
    val expiredCredentials = mutableSetOf<String>()
    val nonDisclosableClaims = mutableSetOf<String>()
    
    val candidatesByRequirement = request.requiredClaim.map { requirement ->
        val candidates = mutableListOf<Candidate>()
        
        for (credential in wallet.credentials) {
            if (!credential.matchesType(requirement)) continue
            if (!credential.matchesRequiredIssuer(requirement)) continue
            
            val claim = credential.claims[requirement.claimName] ?: continue
            
            if (credential.issuer !in trustedIssuers) {
                untrustedCredentials += credential.id
                continue
            }
            
            if (credential.isExpiredAt(nowEpochSeconds)) {
                expiredCredentials += credential.id
                continue
            }
            
            if (!claim.selectivelyDisclosable) {
                nonDisclosableClaims += requirement.claimName
            }
            
            candidates += Candidate(credentialId = credential.id, claimName = requirement.claimName)
        }
        
        if (candidates.isEmpty()) {
            missingClaims += requirement.claimName
        }
        
        candidates.sortedWith(compareBy<Candidate> {it.credentialId}.thenBy{it.claimName})
    }
    
    if (missingClaims.isNotEmpty()) {
        return PresentationPlan.Unsatisfied(
            missingClaims = missingClaims.toSortedSet(),
            untrustedCredentials = untrustedCredentials.toSortedSet(),
            expiredCredentials = expiredCredentials.toSortedSet(),
            nonDisclosableClaims = nonDisclosableClaims.toSortedSet()
        )
    }
    
    val bestSelection = chooseBestSelection(candidatesByRequirement)
    
    return PresentationPlan.Satisfied(
        nonce = request.nonce,
        audience = request.audience,
        selectedCredentials = bestSelection.toSortedMap().map { (credentialId, disclosedClaims) ->
            SelectedCredential(credentialId = credentialId, disclosedClaims = disclosedClaims.toSortedSet())
        }
    )
}

private fun Credential.matchesType(requirement: ClaimRequirement): Boolean {
    return type in requirement.acceptedCredentialTypes
}

private fun Credential.matchesRequiredIssuer(requirement: ClaimRequirement): Boolean {
    return requirement.requiredIssuer == null || requirement.requiredIssuer == issuer
}

private fun Credential.isExpiredAt(nowEpochSeconds: Long): Boolean {
    return expiresAt != null && expiresAt <= nowEpochSeconds
}

private fun chooseBestSelection(candidatesByRequirement: List<List<Candidate>>): Map<String, Set<String>> {
    
}
